# Generated by Django 3.2.3 on 2021-05-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='amount_price',
        ),
    ]
