# Generated by Django 3.2.3 on 2021-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_itemvariation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemspecification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='itemvariation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('id',)},
        ),
    ]
